version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: travel_db
    ports:
      - "3306:3306"

  redis:
    image: redis
    ports:
      - "6379:6379"
